mesh_file: "input/mesh.mesh"
density_file: "input/density.gf"
temperature_file: "input/temperature.gf"
ionization_file: "input/ionization.gf"
laser:
  wavelength: 800e-7
  direction:
    x: -1
    y: 0.577350
  spatial_FWHM: 1e-4
  energy: 1
  start_point:
    x: 140e-4
    y: -50e-4
  end_point:
    x: 140e-4
    y: -10e-4
  rays_count: 100
estimate_bremsstrahlung: true
estimate_resonance: true
estimate_gain: false
rays_output_file: "output/rays.msgpack"
absorbed_energy_file: "output/absorbed_energy.gf"